name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    tags: [ '*.*.*' ]

env:
  IMAGE_NAME: sentinel

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: PrepareReg Names
        id: read-docker-image-identifiers
        run: |
          echo VERSION_TAG=$(echo ${{ steps.version_step.outputs.version_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo LASTEST_TAG=$(echo ${{ steps.version_step.outputs.latest_tag  }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${{env.IMAGE_NAME}}:${{ steps.get_version.outputs.VERSION }} --build-arg version=${{ steps.get_version.outputs.VERSION }} ./
          docker tag ${{env.IMAGE_NAME}}:${{ steps.get_version.outputs.VERSION }} riskers/${{env.IMAGE_NAME}}:${{ steps.get_version.outputs.VERSION }}
          docker push riskers/${{env.IMAGE_NAME}}:${{ steps.get_version.outputs.VERSION }}

